import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import {RouterModule} from '@angular/router';
import {HttpClientModule} from '@angular/common/http';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {ToastModule} from 'ng2-toastr/ng2-toastr';


import { AppComponent } from './app.component';
import { SignUpComponent } from './sign-up/sign-up.component';
import { LoginComponent } from './login/login.component';
import { HttpServiceService } from './http-service.service';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { ChangePasswordComponent } from './change-password/change-password.component';
import { AvailableChatRoomComponent } from './available-chat-room/available-chat-room.component';
import { ChatRoomComponent } from './chat-room/chat-room.component';
import { ChatServiceService } from './chat-service.service';


@NgModule({
  declarations: [
    AppComponent,
    SignUpComponent,
    LoginComponent,
    ForgotPasswordComponent,
    ChangePasswordComponent,
    AvailableChatRoomComponent,
    ChatRoomComponent
  ],
  imports: [
    BrowserModule,HttpClientModule,FormsModule,ToastModule.forRoot(),BrowserAnimationsModule,
    RouterModule.forRoot([
      {path:'login',component:LoginComponent},
      {path:'',redirectTo:'login',pathMatch:'full'},
      {path:'signup',component:SignUpComponent},
      {path:'forgotpassword',component:ForgotPasswordComponent},
      {path:'changepassword/:token',component:ChangePasswordComponent},
      //token here is generated by jwt
      //for password change not user login
      {path:'availablechatroom',component:AvailableChatRoomComponent},
      {path:'chatroom/:chatroomid',component:ChatRoomComponent},
      { path: '*', component: LoginComponent },
      { path: '**', component: LoginComponent }
      ])
  ],
  providers: [HttpServiceService,ChatServiceService],
  bootstrap: [AppComponent]
})
export class AppModule { }
